# Generated by Django

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_add_ssl_verify_to_streamprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragent',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='Full header set to send with this User-Agent. Leave empty to use User-Agent only.'),
        ),
    ]
