# Generated by Django 6.0.3 on 2026-04-26 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_populate_user_agent_headers'),
        ('core', '022_default_user_limit_settings'),
    ]

    operations = [
    ]
