# Generated by Django 6.0.4 on 2026-05-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_systemevent_event_type'),
        ('core', '0026_disable_removed_vod_tasks'),
    ]

    operations = [
    ]
