# Generated by Django 6.0.5 on 2026-06-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_move_preferred_region_and_auto_import_to_system_settings'),
        ('core', '0027_merge_20260507_1724'),
    ]

    operations = [
    ]
