# Generated by Django 6.0.5 on 2026-07-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_vlc_play_and_exit'),
        ('core', '0029_merge_20260702_1808'),
    ]

    operations = [
    ]
