# Generated by Django 6.0.3 on 2026-04-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0017_alter_channelstream_unique_together'),
        ('dispatcharr_channels', '0035_stream_headers'),
    ]

    operations = [
    ]
