# Generated by Django 6.0.4 on 2026-05-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0036_alter_stream_name'),
        ('dispatcharr_channels', '0036_merge_20260404_2125'),
    ]

    operations = [
    ]
