# Generated by Django 6.0.5 on 2026-06-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0037_auto_sync_overhaul'),
        ('dispatcharr_channels', '0037_merge_0036_alter_stream_name_0036_merge_20260404_2125'),
    ]

    operations = [
    ]
