# Generated by Django 6.0.5 on 2026-07-20 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcharr_channels', '0038_add_catchup_fields'),
        ('dispatcharr_channels', '0038_merge_20260601_1808'),
    ]

    operations = [
    ]
