# Generated by Django 6.0.3 on 2026-04-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0022_epgdata_name_textfield_programdata_title_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epgdata',
            name='tvg_id',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='epgsource',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='programdata',
            name='tvg_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
