# Generated by Django 6.0.4 on 2026-05-07 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0022_alter_epgdata_name'),
        ('epg', '0023_alter_epgdata_tvg_id_alter_epgsource_name_and_more'),
    ]

    operations = [
    ]
