# Generated by Django 6.0.5 on 2026-06-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epg', '0024_merge_20260507_1724'),
        ('epg', '0024_remove_epgsource_api_key_epgsource_password_and_more'),
    ]

    operations = [
    ]
